### PR TITLE
Fix Add GPIO type node to set the default max_child_id value

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by twa127** [comment]
Also changed homelist.php to suppress boiler icon when there is an empty boiler table

**Comment by pihome-shc** [comment]
@twa127 after changing homelist.php, its not loading even after about 5 minuts.

**Comment by twa127** [comment]
Strange works on both my main and test systems, it is only a count of boiler table records and then an if condition around the boiler button.

**Comment by twa127** [comment]
If you send me your copy I’ll try this end

**Comment by dvdcut** [comment]
@twa127 
i think even if boiler is not directly controlled by pihome but it display that heating source (boiler) is on when any zone is calling for heat and i think leaving boiler icon in place is good. specially #49 Icon for deadband issue is not fixed and it difficult to know which zone actually calling for heat and which zone is in deadband+weather factor.

**Comment by twa127** [comment]
If we only distribute an empty database then the boiler icon has no data behind it, so I would not display until the boiler record was added to the database

**Comment by dvdcut** [comment]
ok, are you going to modify boiler icon under setting as well? also modifications to boiler.php file as well otherwise you will have errors generated

**Comment by twa127** [comment]
Yes that was the idea, in model you will be able to create the initial boiler record

**Comment by pihome-shc** [comment]
@twa127 i just copy paste this file with all its changes.

**Comment by twa127** [comment]
Can you please try the attached, I've re-formatted the file and found a missing </div> 
[homelist.zip](https://github.com/pihome-shc/pihome/files/4324833/homelist.zip)

**Comment by twa127** [comment]
sorry still not working correctly, I'll work on it

**Comment by twa127** [comment]
Please ignore last comment, I do think it should now be okay, can you test please

**Comment by twa127** [comment]
I'll try again later

**Pull request closed without merging**
