### PR TITLE
Added exception logging and Error handling

### PR DESCRIPTION
**Pull request by MindaugasMeskauskas**
Same update as for serialgw.py.
Have no way of testing, so that still needs to be done.

Added debugging levels
dbgLevel = 3 # 0-off, 1-info, 2-detailed, 3-all
dbgMsgOut = 1 # 0-disabled, 1-enabled, show details of outgoing messages
dbgMsgIn = 1 # 0-disabled, 1-enabled, show details of incoming messages

Added exception logging to file. Writes exception to file /var/www/logs/main.log if script crashes.
Improved exception handling.

Changed logic of battery voltage and percentage insertion to DB. Approach with b_volt variable causes wifigw.py to crash, if variable b_volt is missing if previous part doesn't run before hand. As well there is possibility that battery voltage could be assigned to wrong node, if multiple nodes send battery stats at same time.

### CODE REVIEW

**Comment by pihome-shc** [comment]
i think @twa127  is using serial gateway, he might be able to test this.

**Comment by twa127** [comment]
I've swapped to an Ethernet gateway on my live system but still have a serial one on the RPi test system, so I'll give it a go and let you know.

**Comment by pihome-shc** [comment]
Thank you

**Comment by twa127** [comment]
Hi,

Running on my Ethernet gateway, 2 errors:

line 127 - print "Bytes in outgoing buffer:    ",ser.in_waiting, **_ser is not defined_**
line 247 - print "7: Adding Battery Level & Voltage for Node ID:", node_id, "Battery Voltage:",b_volt,"Battery Level:",payload,"\n\n", **_b_volt is not defined_**

**Comment by twa127** [comment]
Hi,

In the attached I've removed line 127 as I guess in is only applicable to a serial gateway, also changed line 247 to remove the reference to b_volt so its the same as serialgw,py. Tested on my Ethernet gateway and it is working fine including the logging 

[wifigw.zip](https://github.com/pihome-shc/pihome/files/4230338/wifigw.zip)

**Comment by MindaugasMeskauskas** [comment]
@twa127 thank you. pull request updated

**Comment by pihome-shc** [comment]
thank you every one for this work.

**Pull request merged**
