### PR TITLE
Enable creation of new frost protection record if table empty, tidy up email code section

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by dvdcut** [comment]
@twa127 
right now frost_protection table is used in boiler.php, don't know without frost protection entry how boiler.php will react. may be modify boiler.php to add if statement if no frost protection is defined it is set to 0

**Comment by twa127** [comment]
I see setting frost protection as part of the initial system setup, but checking in boiler.php sounds like a good idea. I’ll add to next update.

**Comment by twa127** [comment]
Okay added default frost_protection record creation to boiler.php as a safety measure

**Comment by dvdcut** [comment]
i think same goes for away as well, i suggest to change your approach: may be best to have these changes created during installation.

**Comment by twa127** [comment]
the system has to have some zone created before the boiler script will run successfully, this is why I thought this was a good place to add default away, holidays, night_climate etc.

What do you think?

**Comment by dvdcut** [comment]
Yes you are right, user must have at least one zone before boiler.php can run but what if user do not create away record?. i suggest to moving some default values to install script and it will be less work and less chance of error.

**Comment by twa127** [comment]
away record gets created with the first zone

**Comment by twa127** [comment]
Enabled creation of initial piconnect table entry

**Comment by pihome-shc** [comment]
@twa127 thank you for all the work you are doing lately. 
@dvdcut i think it wouldnt hurt to have some basic configuration in db setup php file.

**Comment by twa127** [comment]
I think we are now at the point where the system can be distributed with a completely empty database and everything can be configured from the GUI, with the exception of the user and system table entries, which are setup in setup_db.php

**Pull request merged**
