### PR TITLE
Schedule GUI tweeks + add/edit just with schedule_add.php

### PR DESCRIPTION
**Pull request by MindaugasMeskauskas**
This includes similar changes I previously submitted for zone_add.php.

- homelist.php
	Added Schedule Name label (sch_name) in Zone Schedule listing model.
- schedule_add.php
	Changed functionality to handle Add and Edit schedule.
	Hide form after submit to display only message.
- schedule_edit.php
	Deleted as no more needed
 - holidayslist.php
	Edited to call only schedule_add.php with right parameters.
	Added Schedule Name label (sch_name) for each Schedule list item.
- schedulelist.php
	Edited to call only schedule_add.php.

### CODE REVIEW

**Comment by pihome-shc** [comment]
should we change schedule_add.php to something more meaning full?

**Comment by MindaugasMeskauskas** [comment]
thought about it for a sec and couldn't think of anything meaningful so I moved on :)
As well didn't want to confuse others if add and edit files disappears.
If you have anything in mind I can update for both zone_add.php and schedule_add.php

**Comment by twa127** [comment]
Hi,

Just started to test this and have hit a problem - with no previous schedules set, the add screen does not display any zones to select. In the old version the // Zone List Loop section fetched the data from the zone table, in the new version a previously populated dataset $zoneresults is used. $zoneresults gets its data from schedule_daily_time_zone_view, I can't workout how this is going to work.

**Comment by pihome-shc** [comment]
i had same problem but i thought i messed my dev system to much and having this issue.

**Comment by MindaugasMeskauskas** [comment]
committed fix, but not sure why another 18 already merged commits were included.

**Comment by twa127** [comment]
Great working now, I'll carry on testing

**Comment by twa127** [comment]
How about changing zone_add.php to simply zones.php and schedule_add.php to schedules.php or scheduling.php

**Comment by pihome-shc** [comment]
we already have schedules.php but scheduling.php and zone.php works

**Comment by twa127** [comment]
gets my vote :-)

**Comment by twa127** [comment]
Tested and found no problems, I do like the multi-use idea, a bit more difficult to follow but less code to maintain ;-)

**Pull request merged**
