### PR TITLE
Node Alerts Lanuage Settings

### PR DESCRIPTION
**Pull request by twa127**
Add language settings Node Alerts and info popover info box for Notice Interval field

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 thank you for update, 
### Father improvement for #56

**Comment by pihome-shc** [comment]
@twa127 
few changes gone missing 
**en.php**
$lang['node_alerts_text'] = "Node Alerts Settings: These settings will help to identify if there is probelm with any Node, This is fail safe. ";

**model.php**
        <th class="col-xs-1">'.$lang['node_id'].'</th>
        <th class="col-xs-4">'.$lang['name'].'</th>
	<th class="col-xs-5">'.$lang['last_seen'].'</th>
        <th class="pull-right text">'.$lang['notice_interval'].'

**Comment by twa127** [comment]
Hi,

$lang['node_alerts_text']  is no longer used in model.php

'.$lang['node_id'].', '.$lang['name'].', '.$lang['last_seen'].' and'.$lang['notice_interval'].' are all included at the bottom of each language file.

**Comment by dvdcut** [comment]
$lang['node_alerts_text'] is [model.php](https://github.com/pihome-shc/pihome/blob/0f5658bf2909bf2e22ff1aea5ab27b6fb73dd734/model.php#L748)
but i think its nice to have this definition on top.

**Comment by twa127** [comment]
Yes but you changed $lang['node_alerts_text'] to $lang['node_alerts_edit_info'] in your first attempt at making it editable, I just thought that text made more sense, so used it in my version :-)

**Comment by pihome-shc** [comment]
@twa127  & @dvdcut 
i think i know where confusion is: 
$lang['node_alerts_edit_info']  is in language file but in model.php it is $lang['node_alerts_text']  thats all,  will fix this later.

**Comment by twa127** [comment]
Correction comitted

**Pull request merged**
