### PR TITLE
Populate GPIO Dropdown Pin List from configuration file

### PR DESCRIPTION
**Pull request by twa127**
Improvement to zone_add.php when GPIO nodes are selected, child IDs are selected from a configuration file

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 
if you edit zone without following query and if statement you will end up with duplicate entries in message_out table 

```
	//check if Controller id already exist in message_out table
	$query = "SELECT * FROM messages_out WHERE node_id = '{$controler}' AND child_id = '{$controler_child_id}' AND zone_id = '{$zone_id}' LIMIT 1;";
	$result = $conn->query($query);
	if ($result) {
		//Add Zone to message out table at same time to send out instructions to controller for each zone.
		if ($node_id !=0 OR $node_id !='0'){
			$query = "INSERT INTO messages_out (node_id, child_id, sub_type, ack, type, payload, sent, zone_id) VALUES ('{$controler}','{$controler_child_id}', '1', '1', '2', '0', '0', '{$zone_id}');";
			$result = $conn->query($query);
			if ($result) {
				$message_success .= "<p>".$lang['zone_controler_success']."</p>";
			} else {
				$error .= "<p>".$lang['zone_controler_fail']."</p> <p>" .mysqli_error($conn). "</p>";
			}
		}
	}
```

**Comment by twa127** [comment]
ah had not picked up #124 will update

**Comment by twa127** [comment]
okay restored that section :-(

**Comment by pihome-shc** [comment]
@twa127 
thank you

**Pull request merged**
