### PR TITLE
Database Table and View change to remove redundant field gpio_pin and use nodes.child_id_1 in boiler and zone views

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 
i think after this merge we'll have bigger problem:  for boiler it is ok as it is only one node and one child node, but for zone it is different story, zone node id is linked and then individual child id set in zone table if child id is removed from zone table then there is only one child id (child_id_1) is defined/recorded in node table. 

When node comes online it presents it self and all child ids but in gateway script ignore all child id and only add node and its related info in node table.

The solution:  As of now node table have child id 1 to 8 in node table and they are not used and child id comes from zone and boiler table. To simplify both tables remove all child id 2 to 8 from node table and rename child_id_1 to child_id and when node first present it self gateway script record all child id and create multiple node records with same node id and all presented child id

node_id | child_id | name | last_seen | notice_interval | status | ms_version | sketch_version | repeater
-- | -- | -- | -- | -- | -- | -- | -- | --
100 | 0 | Boiler Controller |   | 15 | Active | 2.3.1 | 0.34 | 0
101 | 0 | Zone Controller |   | 15 | Active | 2.3.1 | 0.31 | 0
101 | 1 | Zone Controller |   | 15 | Active | 2.3.1 | 0.31 | 0
101 | 2 | Zone Controller |   | 15 | Active | 2.3.1 | 0.31 | 0
101 | 3 | Zone Controller |   | 15 | Active | 2.3.1 | 0.31 | 0

after these change following files need updating: and may be others as well and user need to remove zone and re-create them with correct information, i think this is going to be a major upgrade but this will streamline lots of code and in future other modules can be added i.e i have so many users requesting to add option for light switch/vent fan etc. 

- [ ] wifigw.py
- [ ] serial.py
- [ ] notice.py
- [ ] request.js
- [ ] zone_add.php
- [ ] boiler.php
- [ ] model.php
- [ ] db.php

or any other way of doing this?

**Comment by twa127** [comment]
Ah okay I’ll go away sit in a corner and think about this 😔

**Comment by twa127** [comment]
I see what you mean, it certainly is a bigger change than I first thought.

I never did quite get the child_id_1 to child_id_8 process and I personally think that using a single child_id in the nodes table is a good ideal. 

It could be used as you suggest with multiple entries with the same node_id each with a sequential child_id or an alternative just have a single node_id and use child_id as a counter, this would save space in the node table and I cant see why the data in any other of the fields for that node would need to be different for individual child_ids. It would certainly result in a more streamlined nodes table.

I'm happy to pursue if you wish.

**Comment by pihome-shc** [comment]
yes i was thinking the same to having multiple entries for sake of having different child id is overkill but on same note where you'll put node_child_id for each zone ? i can not see how counter can be used until child_id is defined somewhere in zone table or zone table reference to node table entry for uniqueness.

**Comment by twa127** [comment]
In the zone table could we not uses controler_child_id in exactly the same way as for GPIO pin. The logic being when using GPIO pins we are using a single node_id to identify the GPIO Controller, with controler_child_id to identify the associated GPIO relay pins, then when using a single node_id to identify a Wireless Controller, the associated relays would again be identified by the  controler_child_id

**Comment by twa127** [comment]
Hi,

I've been looking at the existing zone controller sketch and the gateway code. I do not think the auto-detect node code in the gateway is working correctly.

In the sketch the child_ids are presented in a loop:
for (int sensor=1, pin=RELAY_1; sensor<=NUMBER_OF_RELAYS; sensor++, pin++) {
	// Register all sensors to gw (they will be created as child devices)
	present(sensor, S_BINARY);
}
Now S_BINARY will send a type value of 3 to the gateway, but the gateway code checks for a sub_type value of 6, I guess this is incorrect and hence the child_ids are never set. Also although the child_id would be incremented depending on the number of attached relays, the value would only ever be used to update nodes.child_id_1.  Hence using the default zone controller sketch nodes.child_id_1 would be updated 4 times with values 1 through 4.

**Comment by pihome-shc** [comment]
@twa127 yes, we could and we are back to my suggestion where we'll end up multiple entries for same node but different child id. or i m missing something ?

**Comment by pihome-shc** [comment]
> 
> 
> Hi,
> 
> I've been looking at the existing zone controller sketch and the gateway code. I do not think the auto-detect node code in the gateway is working correctly.
> 
> In the sketch the child_ids are presented in a loop:
> for (int sensor=1, pin=RELAY_1; sensor<=NUMBER_OF_RELAYS; sensor++, pin++) {
> // Register all sensors to gw (they will be created as child devices)
> present(sensor, S_BINARY);
> }
> Now S_BINARY will send a type value of 3 to the gateway, but the gateway code checks for a sub_type value of 6, I guess this is incorrect and hence the child_ids are never set. Also although the child_id would be incremented depending on the number of attached relays, the value would only ever be used to update nodes.child_id_1. Hence using the default zone controller sketch nodes.child_id_1 would be updated 4 times with values 1 through 4.

sorry we both replied at the same time: 
yes you are right child ids are ignored in gateway script, zone controller code present its child ids through the loop but script do not record this information all number of child are hard coded in zone creation code. but i think this has to change to streamline the code. sorry didnt get what you are suggesting

**Comment by twa127** [comment]
Nope we would have a singe node table entry say node 101, with child_id say set to 3, indicating 3 attached relays. Then the zone table the controler_id would be 101 for all zones connected to that controller and the zone table controler_child_id would indicated the relay number. Exactly the same principle as using the Pi as a zone controller.

**Comment by pihome-shc** [comment]
ok, now i think i understand you, and agree with child_id set to number of child presented by controller and remove rest of the child ids as they are not used anywhere. so zone table will stay the same with node id link to node table and have its own child id saved. did i understood you right?

**Comment by twa127** [comment]
Yes that was the idea, if you think its the way to go I'll modify my test system and see what the other implications are.

**Comment by pihome-shc** [comment]
ok good, i think this way no major changes from end user as it still reference zone and child id same way. thank you for your effort.

**Comment by twa127** [comment]
Hi,

How do you feel about changing the sensor_child_id to start at 1 rather than 0, this would align with the controler_child_id which already starts at 1 for MySnRF and I2C controllers. There would be no need to change the sketch, we could do it in the gateway script.

**Comment by pihome-shc** [comment]
i know it is better to have child id start from 1 same as zone valve but i think its not very important and can be ignored. 
Changing it in gateway script or in table view queries will cause confusion. if sensor_child_id were to change then it also mean users have to create their zone again. may be it is better to leave sensor_child_id as it is, what ever is coming from sensor. Is there any other reason you want to align sensor_child_id with zone_child_id?

**Comment by twa127** [comment]
No I was just trying to be Mr Spock and keep it logical :-)

I do think it might be a good idea to change the field mane from child_id_1 as we will be dropping the other child_id_x columns. How about max_child_id rather than just child_id as the value stored is not actually the id

**Comment by pihome-shc** [comment]
That child_id_1 can be any thing, i mean any name or value but real problem is where to save child id to keep is consistent and easy to implement in future modules. 
Can we not drop all child id_x from nodes table all together? Or have max-child-id column but what purpose it will serve? 

At this point n time child id comes from zone table.

**Comment by pihome-shc** [comment]
@twa127 i was thinking about this while i was sitting at barber shop  :)
let say if i have to add light switch on main screen on main screen then what is required, how we go about adding that option and then trigger it and that trigger has to be instant. 
my head is melting, more and more i m thinking about it more and more i m getting confused.  :(

**Comment by twa127** [comment]
My thoughts:
1. Say we start with and empty database
2, The first thing I would do would to add the nodes, ie Sensors and Controllers. At this point for auto-detected sensors and controller, the number of child_ids would be known. For says an i2c controller we would know the number of attached relays ie the number of child ids.
3. The next thing would be to add the zones, selecting the sensors and controllers as required, the number of child_ids selectable would be as defined in the nodes table.

From the above I would argue for a max_child_id value in the nodes table. This value used to determine selectable values for the zone add/enter screen sensor child ID and controller child ID.

As for the light switch, is that just basically another relay controller, which again could either be a single relay of with multiple relays as child_ids. Not sure how we could do an instant trigger, but on my system I have a cron job which resets the boiler from database entry set by a main screen button.

**Comment by pihome-shc** [comment]
max child id to determine delectable values for zone and sensors and light switch is good idea, same will not apply to I2C and GPIO numbers as they are not presented automatically, user must add them as node. 
light switch will get slightly different treatment, they will be added as normal nodes and directly goes to message_out table and insistently message sent out same as boost console. 
now million dollar question what is the plan now?

**Comment by twa127** [comment]
I was thinking that for ithe i2c relay numbers and the GPIO pin numbers the node table still contains the number of relays connected to the controller, the actual relay or GPIO pin number is held against the zone in the zone table controler_child_id column. This way all the controller types function in the same way.

I'm happy to take on the coding if you want, I'll email the changed files and that way you can decide if you like the approach and test before committing the changes.

**Comment by pihome-shc** [comment]
Ok, yes if you can spare some time for this update, thank you for your effort

**Comment by dvdcut** [comment]
interesting conversation: one thing to add here dont forget to modify **cron/gpio_ds18b20.py** as well to include wired temperature sensors in this change

**Comment by twa127** [comment]
Okay will do

**Comment by twa127** [comment]
Attached are the changes to implement the new node table format. the value used for max_child_id should be:

1. For GPIO nodes - the highest pin GPIO pin number to be used
2. For i2c nodes - the number of relays attached to the i2c board
3. Sensors will be auto-discovered, the value will be number of sensors attached to the node - 1
4. Controllers will be auto-discovered, the value will be number of relays attached to the node

I've also changed Add/Edit Zone so that the drop down lists for sensor and controller child ID are dynamically populated based on nodes.max_child_id.

[Node Table Update.zip](https://github.com/pihome-shc/pihome/files/4209525/Node.Table.Update.zip)

Please let me know what you think.

**Comment by pihome-shc** [comment]
@twa127 thank you, 
i will check your code later in the evening but this updated covers #126 GPIO for Zone and Boiler issue?

**Comment by twa127** [comment]
I think it does, but from a slightly different angle, the principle is:

1. The nodes table defines the configuration of the node itself, its type - MySnRF, GPIO, i2c, its name - Temperator Sensor, Zone Controller or Boiler Relay, its identification - node_id and the number of devices attached to the node itself - max number of GPIO pin, number of relays or number of sensors (minus 1). The nodes table is simplified in that you only have a single entry for a node (ie node_id = 0 identifies the Raspberry Pi as a GPIO pin controller, which can be used in either the zone or relay tables), the individual devices attached to the node are identified in either the zone or relay tables. A single column max_child_id replaces the current 8 child_id_x columns.

2.There are no changes required to the zone or boiler table/views as the sensor_child_id, controler_child_id and boiler.node_child_id fields are already used to identify the GPIO pin number or relay number.

3. For auto-detected nodes, no change is required for the sketches, the gateway scripts ate modified to cope with controller types (this is missing from the current scripts). 

4) The Nodes setting option for GPIO and i2c nodes now uses the maximum number of devices attached to the node, in the case of GPIO nodes, the highest GPIO pin number value is used. 

5) In the Zone settings option both the dropdown lists for Temperature Sensor Child ID and Zone Relay Controller's Child ID are defined dynamically dependent on the values selected for Temperature Sensor ID or  Zone Controller ID.

**Comment by pihome-shc** [comment]
Hi @twa127, 
great work as always. 
user only need to add one gpio entry in node table as gpio pin is saved in zone table, and by default there is already one in table but for i2C nodes user must create each board with max relays attached to board. wireless nodes are discovered so no change required for wireless nodes. 

Following suggestions: 
- Remove Boiler Notice alert from boiler so all notice related settings are under one location. 
- Add GIOP Text along with 0 i.e. GPIO-0, user dont need to add multiple GIOPs its already there but we can leave it there. 
- Add I2C text along with I2C board number i.e. I2C-20
- MySnRF  for MySensor wireless nodes may be isnt good value they could be RFM wireless and treatment is same so may be MySensor would be better? 
- List of GPIO can not be max number as not all gpio pins are useable. May be this one needs to be hardcoded. 

wiringpi_installation

**Comment by twa127** [comment]
Hi,

Okay Will take on-board your suggestions, a couple of things:

1. How about a new controller type called 'GPIO Controller', this could be used for both the zone and boiler relays, Thought it makes logical sense.

2. My list of available GPIO pins is different to yours as I don't use an RPi, so perhaps the list of available pins could be in config.ini

3. At present the boiler model does not work correctly, I'll work out an update

**Comment by pihome-shc** [comment]
GPIO Controller is good option, then user dont need to create zone and boiler separately, may be same for I2C as well? 
i think leave gpio list as you have, any user who is using gpio should know what he/she is doing.

**Comment by twa127** [comment]
ok

**Comment by twa127** [comment]
I've taken on board your comments, with the exception of the GPIO pin number dropdown.

I've added 2 new controller types - 'GPIO Controller' and 'I2C Controller'. The logic been that a single GPIO Node (ie the RPi) or single I2C relay block could be used to control both zone valves and the boiler using individual relays connected to the controller and identified by the child_id

Please find attached update and let me know what you think.

[Node Table Update.zip](https://github.com/pihome-shc/pihome/files/4221046/Node.Table.Update.zip)

**Comment by pihome-shc** [comment]
@twa127 
First of all it is great improvement and i genuinely appreciate your effort. Two small changes and after this you can do pull request and this will be version 1.73 release. 

first:
settings->nodes->add-node have four type of controllers, gpio, i2c, zone and boiler controller, i think we dont need zone and boiler controller as options here. only for i2c and gpio is enough, i see goiler model and zone_add can see i2c and gpio as multi type controller. 

second: 
these changes in model.php and in zone_add.php 
I2C-<board number>
GPIO instead of 0

**Comment by twa127** [comment]
For the second point how do you like this:
image

The reason being is that although there is only likely to be one GPIO controller, you may have multiple I2C modules

**Comment by pihome-shc** [comment]
@twa127 that looks good, just noticed that info text, may be changed that to Select Zon Controller

**Comment by twa127** [comment]
Already caught that one :-)

image

**Comment by twa127** [comment]
Also found an issue with homelist.php when reporting errors for boiler and controller not reporting within the notice interval. If the GPIO or I2C controller is made 'Active' in the zone table, then this causes the issue, as these devices do not report last_seen back to the node table (obviously).

A work around would be to leave nodes.status set to NULL, but I think a more logical solution is to check type='MySensor' in homelist.php for the boiler and status last reported tests

**Comment by pihome-shc** [comment]
you have to change db query to set notice_interval to 0 to get this working properly.

**Comment by twa127** [comment]
Okay why not just set notice_interval to 0 whenever we create a GPIO or I2C node?

**Comment by pihome-shc** [comment]
@twa127 sorry if wasn't clear that is what i meant

**Comment by twa127** [comment]
Okay great, done that, another thought - in the Add Nodes model we don't need to enter the zone name as that will be either 'GPIO Controller' or 'I2C Controller' and we can generate that in request.js using the node type. Lastest update attached.

[Node Table Update.zip](https://github.com/pihome-shc/pihome/files/4225624/Node.Table.Update.zip)

**Comment by pihome-shc** [comment]
@twa127 you mean Node Name? yes we dont need Node name as this can be generated in request.js and pass to db.php file.

**Comment by twa127** [comment]
Yep sorry did mean Node Name, I've implemented it that way in the last update I sent you

**Comment by pihome-shc** [comment]
@twa127 that all worked great, i think its ready for merge.

**Comment by twa127** [comment]
okay will do, it will impact #133 as I've changed wifigw.py

**Comment by twa127** [comment]
update the pull request

**Comment by twa127** [comment]
This update also fixes an issue with boiler.php when the number of zones is not equal to 3, $zone_log is currently checked in a for/next loop with an index of 3, this is changed to count($zone_log)

**Comment by twa127** [comment]
oops forgot MySQL_View.sql changes for child_id_1

**Pull request merged**
