### PR TITLE
Update check_gw.php

### PR DESCRIPTION
**Pull request by dvdcut**
Gateway Script fix:  updating date and time in gateway_log table.

### CODE REVIEW

**Comment by twa127** [comment]
Hi,

Won't this put the current datetime and not the process start time?

**Comment by twa127** [comment]
Looking at check_gw.php, perhaps when find gateway is executed it should insert a record in to the gateway_logs table

**Comment by dvdcut** [comment]
@twa127 that is right, gateway_logs only gets updated if gateway.py isnt running and it will start that script and take note of its running date time. previously it was saved in pid_start_time (char) and this couldnt be calculated for anything only for visual, and pid_start_time was set to timestamp with default current_timestamp(), now after #166 default value is removed so i m updating it with php script. 

i dont know how to get correct date time format with ps command.

**Comment by dvdcut** [comment]
inserting record for gateway search isnt good, becasue it will add another records and search logic counts how many records in last 10 minutes

**Comment by twa127** [comment]
I assumed that the search only runs if $find_gw == 1 which is cleared after the search has run. My thinking was that when the system is initially set up the 'Search Gateway' option would be used and thus create the initial gateway_logs record.

Also pid_datetime record needs to be updated as it previously picked up the default value.

**Comment by twa127** [comment]
Could also add a gateway_logs record when 'Save' is used on the Gatway settings GUI, this again would ensure that gateway_logs table was not empty

**Comment by twa127** [comment]
Just tested the last last suggestion and it worked okay

**Comment by dvdcut** [comment]
logs gets filled when you have wrong ip for gateway, and system will try to connect on old ip and fails and this way check_gw.php keeps adding records to log table until it reaches to greater then 9 and in next run instead of trying to run script check_gw.php will start the search for gateway. 

just noticed one more thing, if i disable gateway from gui then exiting process keeps running, dialing  it wouldn't kill that process.

**Comment by twa127** [comment]
Can't do much about testing the ip address issue as my test system has a serial gateway, I'll have a look at the code and see if I can suggest anything.

I think the initial problem with the empty gateway_logs table is best fixed by creating an initial entry when the gateway is first setup

**Comment by twa127** [comment]
Hi,

Looking at this update again, I think it may be wrong. 

I think pid_start_time is fine as it is, the problem is that pid_datetime is not being inserted, so the datebase structure is fine and the query should be -
$query = "INSERT INTO gateway_logs (`sync`, `purge`, type, location, port, pid, pid_start_time, pid_datetime) VALUES ('0', '0', '{$gw_type}', '{$gw_location}', '{$gw_port}', '{$out[0]}', '{$pid_details}', '{$date_time}' )";

**Comment by dvdcut** [comment]
i have updated column datatype, but you are right, without modifying anything i.e database, i can simply change code to update pid_datetime and then update db_cleanup.php and check_gw.php need little bit change as well.

**Comment by twa127** [comment]
I think db_cleanup.php and probably check_gw.php are okay as pid_datetime will be valid for any records present

**Comment by dvdcut** [comment]
i think i know what you mean, i have updated the pull request

**Comment by dvdcut** [comment]
sorry for this, i think i made big mess, i m closing this pull request and do new one.

**Pull request closed without merging**
