### PR TITLE
Circulation Pump Overrun #263 settings from gui

### PR DESCRIPTION
**Pull request by dvdcut**
Circulation Pump Overrun #263 option to change settings from gui under settings->boiler

### CODE REVIEW

**Comment by dvdcut** [comment]
Thanks to @aszumski for doing all the back end work.

**Comment by aszumski** [comment]
@dvdcut  can you please add "-1" option in model.php less than 0 keeps valve open until next boiler start.

**Comment by dvdcut** [comment]
@aszumski added option and 0 mean disable the overrun?
```
<option value="-1">Keep valve open until next boiler start</option>
<option value="0">Disable</option>
```

**Comment by aszumski** [comment]
@dvdcut  that's great thanks.

**Comment by pihome-shc** [comment]
@dvdcut  thank you.

**Pull request merged**
