### PR TITLE
Fix for Add Schedule

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by twa127** [comment]
gateway.py got included as well but not changed

**Comment by pihome-shc** [comment]
@twa127 
line 303 have `<?php echo $check;?>`  which shows when editing schedule. i think  you had it for some debug. 

#190 Add Schedule - Enable Zone do not work properly

**Comment by twa127** [comment]
line 303 was already there in your current version
what's the issue with Enable Zone?

**Comment by pihome-shc** [comment]
ok, no worries, may be remove this line in next pull request.

**Comment by twa127** [comment]
Went back to feb and it was still there

**Comment by twa127** [comment]
in fact it appeared in the first version of scheduling.php was not in the last copy of schedule_add,php

**Comment by pihome-shc** [comment]
@twa127
sorry my mistake, did notice this before, i will update this and one small change with top menu icon size for settings.

**Pull request merged**
