### PR TITLE
Enable Selection of which heatings zones should be included in the graph

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 
looks great, as alternate have look here another way of enabling and disabling graph, i m not sure if it is compatible with PiHome graph. 
http://www.jqueryflottutorial.com/jquery-flot-toggling-series-manipulation.html
http://www.flotcharts.org/flot/examples/series-toggle/index.html

**Comment by twa127** [comment]
fixed truncated line error in model.php

**Comment by pihome-shc** [comment]
@twa127 Thank you, i think this update would help in my next installation of PiHome with 32 zone, and graph really become difficult to read with all that data in small screen.

**Comment by twa127** [comment]
Glad to be of help, thats a lot of zones, commercial property I guess 

Regards 

Terry

**Comment by pihome-shc** [comment]
Its residential property but little bit bigger,

**Pull request merged**
