### PR TITLE
Temperature deadband

### PR DESCRIPTION
**Pull request by aszumski**
Added temperature deadband, zone starts when temperature is below setpoint-deadband and stops when temperature is greather or equal to setpoint.

### CODE REVIEW

**Comment by aszumski** [comment]
Sorry for messy push request still trying to figure out github.
Can you please resolve the issue for SQL file.
I don't want to mess it up anymore.

On SQL side I've only added:
'sp_deadband' in 'zone' table
and
'zone.sp_deadband' to 'zone_view' zone

**Comment by pihome-shc** [comment]
@aszumski did you test this? i haven't changed any significant amount of code in boiler.php for long time as this is the core of PiHome.

**Comment by aszumski** [comment]
@pihome-shc 
Yes, I've tested it for all scenarios, frost protection, schedule, override, night climate and boost.
Probably it would be no harm if someone else have a quick test as well.
Added different message for hysteresis cause initially when I was testing I got message about max temp reached and was wondering what did I brake.

With the deadband approach I've implemented it would be easy to use both low and high setpoint in night climate (it currently uses low setpoint only) just use low setpoint to cut in and high to cut out.

One thing I've spotted is that indication for zone active on the main screen wont work accurately cause it's based on temperature only and within a deadband zone can be on or off.
It wasn't 100% accurate anyway before my change it didn't account for weather factor and midnight rollover change for schedule.

I think it would be good Idea to have zone_status table in database that would keep current zone status like frost protection status, night climate status, override status, boost status, current temperature setpoint, zone command, maybe fault status if its implemented. Populate that data in boiler.php.
And then use that in homelist.php instead of replicating code from boiler.php to get your schedule/night climate status, temperature setpoint etc. that way you always get accurate data on the screen and  you don't have the problem of files getting out of sync.

**Comment by pihome-shc** [comment]
@aszumski 
conflict is resolved, all table views are moved to setup_db.php and MySQL_View.sql file.

**Comment by twa127** [comment]
Might be worth making the default table value zero rather than 0.5, this way deadband will not be automatically enabled.

**Pull request merged**
