### PR TITLE
Unified credentials

### PR DESCRIPTION
**Pull request by sandreialexandru**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@sandreialexandru 
something isnt right for wifigw.py here is result 

`Traceback (most recent call last):
  File "/var/www/cron/wifigw.py", line 35, in <module>
    con = py_access.get_connection()
  File "/var/www/cron/py_access.py", line 8, in get_connection
    _connection = mdb.connect(host="localhost", user = "root", password = "passw0rd", dbname = "pihome")
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: 'dbname' is an invalid keyword argument for this function
`

**Comment by sandreialexandru** [comment]
I'll try to change the parameters in py_access.py with default ones.
"password" should be named "passwd" and "dbname" should be "db". Unfortunately I have no access to my laptop at the moment.

**Comment by sandreialexandru** [comment]
As a guideline, the connection constructor parameters should be
implemented as keyword parameters for more intuitive use and follow this
order of parameters: host, user, passwd, db

**Comment by sandreialexandru** [comment]
I have updated **py_access**. Please let me know if any other errors occur as I can't test at the moment.

**Comment by pihome-shc** [comment]
@sandreialexandru Thank you it worked this time. 
#88 single non updated config file for database ip/user/pass

**Pull request merged**
