### PR TITLE
#368 Enable Multiple controllers per Zone. NOTE: execute migrate_controller.php in the MySQL_Database directory to update the database DO NOT USE update_db.php

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 this update does require database update for this to work?

**Comment by twa127** [comment]
Yes but migrate_controller.php  takes care of that, it creates the new table zone_controllers, modifies the zone table and updates the zone_view

**Comment by pihome-shc** [comment]
should we do new release now? i.e 1.77?

**Comment by twa127** [comment]
Yes good point as the database structure has changed, perhaps the code for the version update need to be included in migrate_controllers.php as not using update_db.php, what do you think ?

**Comment by pihome-shc** [comment]
yes  that is right, also i need to get #391 completed before next release. as it is very critical we have way to communicate with user and send update alerts.

**Comment by twa127** [comment]
okay I'll add to migrate_controllers.php and set version to 1.77

**Comment by twa127** [comment]
Okay added to the commit

**Comment by pihome-shc** [comment]
#392
#391
#388
#368

**Pull request merged**
