### PR TITLE
Added MQTT capability and various management.

### PR DESCRIPTION
**Pull request by paulcsf**
Added MQTT capability and various management.
One sensor supported presently, should be easy to extend with more sensor
types.
Requires database changes notated in the cron/mqtt.py file, and here:
CREATE TABLE `pihome`.`mqtt` ( 
    `id` INT NOT NULL AUTO_INCREMENT , 
    `name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '' , 
    `ip` VARCHAR(39) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '127.0.0.1' , 
    `port` INT NOT NULL DEFAULT '1883' , 
    `username` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '' , 
    `password` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '' , 
    `enabled` TINYINT NOT NULL DEFAULT '1' , 
    `type` INT NOT NULL DEFAULT '0' ,
    PRIMARY KEY (`id`)) ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_520_ci;
INSERT INTO `mqtt` (`id`, `name`, `ip`, `port`, `username`, `password`, `enabled`, `type`) VALUES (NULL, 'Demo', '127.0.0.1', '1883', 'mosquitto', 'mosquitto', '0', '0');

### CODE REVIEW

**Comment by pihome-shc** [comment]
@paulcsf Thank you for your hard work, love the services icon in settings and great work on MQTT

**Comment by pihome-shc** [comment]
@paulcsf do you have instruction how to use MQTT with PiHome? 

i tried to install service but i m getting service unknow and with following message. 
-- Logs begin at Thu 2016-11-03 17:16:42 GMT, end at Sun 2019-03-10 01:14:01 GMT. --
Mar 10 00:56:52 pihome.local systemd[1]: pihome.mqtt.service: Unit entered failed state.
Mar 10 00:56:52 pihome.local systemd[1]: pihome.mqtt.service: Failed with result 'exit-code'.
Mar 10 01:11:02 pihome.local systemd[1]: Started PiHome MQTT Service.
Mar 10 01:11:03 pihome.local python[1858]: Traceback (most recent call last):
Mar 10 01:11:03 pihome.local python[1858]: File "/var/www/cron/mqtt.py", line 4, in
Mar 10 01:11:03 pihome.local python[1858]: import paho.mqtt.client as mqtt
Mar 10 01:11:03 pihome.local python[1858]: ImportError: No module named paho.mqtt.client
Mar 10 01:11:03 pihome.local systemd[1]: pihome.mqtt.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 01:11:03 pihome.local systemd[1]: pihome.mqtt.service: Unit entered failed state.
Mar 10 01:11:03 pihome.local systemd[1]: pihome.mqtt.service: Failed with result 'exit-code'

**Comment by paulcsf** [comment]
To install Mosquitto on the PI (if you need a local MQTT broker):
```
sudo apt update
sudo apt install mosquitto mosquitto-clients
sudo systemctl enable mosquitto.service
mosquitto -v
```

Create /etc/mosquitto/conf.d/mosquitto.conf file and put the following in it:
```
user mosquitto
max_queued_messages 200
message_size_limit 0
allow_zero_length_clientid true
allow_duplicate_messages false
 
listener 1883
autosave_interval 900
autosave_on_changes false
persistence true
persistence_file mosquitto.db
allow_anonymous true
password_file /etc/mosquitto/passwd
```
Reload the configuration without restarting the server:
```
ps -A | grep mosquitto
sudo kill -HUP <PID#>
```


Add user mosquitto (ORIGINAL create of password file):
```
cd /etc/mosquitto
sudo mosquitto_passwd -c passwd mosquitto
   <enter mosquitto twice for password>
sudo systemctl restart mosquitto
```

To add another user (ex Sonoff Tasmota default user, DVES_USER:DVES_PASS):
```
sudo mosquitto_passwd passwd DVES_USER
  <enter DVES_PASS twice for password>
sudo systemctl restart mosquitto
```

**Comment by paulcsf** [comment]
For the MQTT Python script to work:
```
sudo pip install paho-mqtt
sudo pip install mysqlclient
```
A simple script to watch all MQTT traffic flowing through a server (test.py):
(See [https://pypi.org/project/paho-mqtt/](url) for more info/details)
```
import paho.mqtt.client as mqtt

MQTT_SERVER = "localhost"
MQTT_PATH = "#"

# The callback for when the client receives a CONNACK response from the server.
def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    # Subscribing in on_connect() means that if we lose the connection and
    # reconnect then subscriptions will be renewed.
    client.subscribe(MQTT_PATH)

# The callback for when a PUBLISH message is received from the server.
def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))
    # more callbacks, etc

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message
client.connect(MQTT_SERVER, 1883, 60)
client.loop_forever()
```
Test with:
```
mosquitto_pub -u mosquitto -P mosquitto -d -t hello/world -m "Hello from terminal"
```

**Comment by pihome-shc** [comment]
@paulcsf 
i m getting following error. 

root@pihome:~# mosquitto -v
1552408797: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1552408797: Using default config.
1552408797: Opening ipv4 listen socket on port 1883.
1552408797: Error: Address already in use

**Comment by paulcsf** [comment]
`mosquitto -v` is not a version command, but start it in verbose mode. Sorry about that, I updated the directions above.
`mosquitto -h` will display help but also the version. 

If mosquitto is running, the command ('mosquitto -v') will respond:
```
pi@radiantpi:~ $ mosquitto -v
1552410825: mosquitto version 1.4.10 (build date Wed, 17 Oct 2018 19:03:03 +0200) starting
1552410825: Using default config.
1552410825: Opening ipv4 listen socket on port 1883.
1552410825: Error: Address already in use
```
That's fine, it is already running and can not open the port again. If it was not running, it will start and run in the CLI, printing all messages to the console. 

To see what ports are open and by which programs:
```
pi@radiantpi:~ $ sudo netstat -lptn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      477/mysqld
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      365/vncserver-x11-c
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      384/sshd
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      322/mosquitto
tcp6       0      0 :::5900                 :::*                    LISTEN      365/vncserver-x11-c
tcp6       0      0 :::80                   :::*                    LISTEN      478/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      384/sshd
tcp6       0      0 :::1883                 :::*                    LISTEN      322/mosquitto
```

**Comment by pihome-shc** [comment]
@paulcsf Thank you for taking time and explaining this, i can not test this as i dont have any mqtt device but it looks like that your update receive temperature readings from Sooff - Tesmota.

**Comment by mindaugas111** [comment]
Hi, could you explain how to do it in version 1.76.
I have mosquitto mqtt broker installed and running.
I have /var/www/cron/mqtt.py running.
How to add sensor to the application?

**Comment by scottagecheeseandcrackers** [comment]
@paulcsf - can I ask your help on this. Just setup up my first Tasmota Temperature Sensor, and am now attempting to add it as a node in PiHome. Tasmota is working fine - sensor data outputting as normal. No issues with mosquitto as I use it for other devices aswell - without issue.

When I run /var/www/cron/mqtt.py I get the following output....and no new nodes appear in phpmyadmin...

```
Connected with result code 0
^CTraceback (most recent call last):
  File "mqtt.py", line 162, in <module>
    time.sleep(0.1)
```

Can you help me out. Where am I going wrong?

**Pull request merged**
