### PR TITLE
Update database files to match post Migrate Controllers change. Include #409 change

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 can i run update on version 1.77 for database?

**Comment by twa127** [comment]
No, this is for a new installation. To get from 1.77 to 1.78 you would need to execute migrate_controller.php. I've left this update until now so that hopefully it has given existing users enough time to migrate to 1.78

**Comment by pihome-shc** [comment]
@twa127 you mean from 1.76 to 1.77?

**Comment by twa127** [comment]
Yes you are correct migrate_controller.php brought the database up to version 1.77

**Pull request merged**
