### PR TITLE
Update check_gw.php

### PR DESCRIPTION
**Pull request by dvdcut**
Gateway Script fix: updating date and time in gateway_log table.
sorry had to do this again, not expert on github,

### CODE REVIEW

**Comment by twa127** [comment]
Morning,

The OR $gw_status == '0' will mean that for disabled gateways the code will be executed every time the script runs and you will be trying to kill a process which is not running and also updating the the reset column value to 0 when it is already 0.

**Comment by dvdcut** [comment]
good morning, 
i think then it need to be taken care of at the time of saving gateway setting in db.php.

**Comment by twa127** [comment]
Hi,

What do you think of this - changed the query so as not to check status = 1, then used if else depending on the value of status column and if status = 0 then only stop the process if it is running

[check_gw.zip](https://github.com/pihome-shc/pihome/files/4528177/check_gw.zip)

**Comment by dvdcut** [comment]
what are the chances some other process would have same id in few hours/days or months time? i suggest to introduce some modifications to db.php for this work.

**Comment by twa127** [comment]
Good point, could just identify it by name but the rest check_gw is using pid anyway

**Comment by dvdcut** [comment]
yes, i think that is another way of doing this, but modifying db.php will action this once only, but if we modify check_gw.php it will do this every time this script run.

**Comment by twa127** [comment]
if we do it it db.php we would need javascript executed on a trigger event on the enabled checkbox, would still need to identify the PID from the gateway table and assume it is valid, which in fact it should be as it will be kept valid by check_gw cron job, and then check if running before kill.

Going back to your point about the PID not being valid - it should be valid because that's what check_gw.php does for a living. The overhead if checking status in check_gw.php is minimal as the table has been read anyway and we are already doing exactly the same for reboot. Bottom line is much less code to do it in check_gw.py, just set a variable from the status column and an if test

**Comment by dvdcut** [comment]
good point, so lets modify check_gw.php.

**Comment by twa127** [comment]
:-))

**Comment by twa127** [comment]
Tidied up copy attached if you need it

[check_gw.zip](https://github.com/pihome-shc/pihome/files/4528811/check_gw.zip)

**Comment by twa127** [comment]
oops sorry forgot to put the new INSERT query in that

**Comment by twa127** [comment]
This should be okay
[check_gw.zip](https://github.com/pihome-shc/pihome/files/4528933/check_gw.zip)

**Comment by dvdcut** [comment]
what do you think of this: 
```
//if status set to 0 then check if gateway PID is running and if found then kill
if ($gw_status == '0') {
	//Gateway Python Script location
	$gw_script_txt = 'python /var/www/cron/gateway.py';
	//Check if Porocess is running and get its PID
	exec("ps aux | grep '$gw_script_txt' | grep -v grep | awk '{ print $2 }' | head -1", $out);
	if (count($out) > 1) {
		echo "\033[36m".date('Y-m-d H:i:s')."\033[0m - Gateway PID is: \033[41m".$out[0]."\033[0m \n";
		echo "\033[36m".date('Y-m-d H:i:s')."\033[0m - Stopping Python Gateway Script \n";
		//Kill Gateway Python Scrip PID
		exec("kill -9 '$out[0]'");
	} else {
		echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Gateway is DISABLED \n";
	}
} else {
	//if reboot set to 1 then kill gateway PID and set reboot status to 0
	if ($gw_reboot == '1' OR $gw_status == '0') {
		echo "\033[36m".date('Y-m-d H:i:s'). "\033[0m - Stopping Python Gateway Script \n"; 
		exec("kill -9 $gw_pid");
		$query = "UPDATE gateway SET reboot = '0' LIMIT 1;";
		$conn->query($query);
		echo $line;
	}
```

**Comment by twa127** [comment]
Looks good to me

**Comment by twa127** [comment]
Have you lost reboot, I couldn't see it

**Comment by dvdcut** [comment]
oops, added reboot section now,

**Pull request merged**
