### PR TITLE
Sync homelist zone status with boiler.php #49 

### PR DESCRIPTION
**Pull request by aszumski**

### CODE REVIEW

**Comment by aszumski** [comment]
This got little bit messy as @twa127 was working on boiler and homelist at the same time.
@twa127 or @pihome-shc can you resolve conflicts, I'm not good with git and will probably make total mess out of it.

**Comment by pihome-shc** [comment]
this is going to be fun

**Comment by twa127** [comment]
if you want to backout the changes to boiler.php and homelist.php, I can always do them again

**Comment by twa127** [comment]
The new field in the zone table will take care of current state, maybe :-)

**Comment by twa127** [comment]
maybe not the as change to boiler.php is quite extensive.  I can re-think my code if you want to implement this change first

**Comment by aszumski** [comment]
@twa127 leave your changes on the master, I will branch of the current master tomorrow  and try to implement my changes there, it will be easier than merging it.
Not sure how people manage it in big real life project, must be a nightmare :)

**Comment by twa127** [comment]
okay whatever works best, I may re-think some of my change based on your new table.

I was part of BT software development department many years ago and yes configuration management was nightmare :-)

**Comment by twa127** [comment]
by the way you may want to tweek your new table as we have removed all the default values from the database setup

**Comment by twa127** [comment]
@aszumski  see what you think about the attached boiler.php, I've included both sets of changes, it need tha latest zone table and zone_view to work
[boiler.zip](https://github.com/pihome-shc/pihome/files/4782472/boiler.zip)

**Comment by pihome-shc** [comment]
sorry guys i was locked out of my house today :( what is the final verdict ?

**Comment by twa127** [comment]
@aszumski  attached homelist.php with both your and my changes

[homelist.zip](https://github.com/pihome-shc/pihome/files/4782902/homelist.zip)

hopefully this should remove the conflicts

**Comment by twa127** [comment]
not quite right yet, not getting temps

**Comment by aszumski** [comment]
@twa127 I didn't have time to test it today.
If you went through the effort of combining changes, there is no point for me to do it again.
I will test your files tomorrow morning.

**Comment by twa127** [comment]
@aszumski  okay great, let me know how it goes, attached an updated version of homelist,php which now gets the temperatures

[homelist.zip](https://github.com/pihome-shc/pihome/files/4783179/homelist.zip)

**Comment by aszumski** [comment]
just tried to update database I get some errors:
`ySQL Database Error with Query ALTER TABLE `piconnect` MODIFY PRIMARY KEY (`id`) USING BTREE;
:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'PRIMARY KEY (`id`) USING BTREE' at line 1
MySQL Database Error with Query ALTER TABLE `zone` DROP `boiler_id`;
:Cannot drop index 'FK_zone_boiler': needed in a foreign key constraint
`
For the second error boiler_id was removed from the table but the foreign key definition was left.
Not sure what's wrong with the first one.
Will run some tests now.

**Comment by aszumski** [comment]
where can I get latest definition for zone table.
master is missing zone_type column, not sure what else

**Comment by twa127** [comment]
attached sql for latest zone table and view

[sql.zip](https://github.com/pihome-shc/pihome/files/4785826/sql.zip)

**Comment by aszumski** [comment]
i can see zone types can be defined in settings

**Comment by twa127** [comment]
yep basic ones are Heating And Water, select 'Sensor and Boiler Control'

**Comment by aszumski** [comment]
@twa127 I think it works OK 
Only thing I don't like is that if you are in holidays mode and there is no holiday schedule active  for current time you can't turn on the boost.
But this is existing issue and has nothing to do with our changes.

Should boiler_id column be in the zone table or not?
it's not in the github sql config file.
If it's removed it breaks zone edit/add.

I've created new pull request with your files.
Closing this one.

**Comment by twa127** [comment]
Hi,

@pihome-shc asked me to remove boiler_id, we have a new version of zone.php which I've not yet committed, attached below

[zone.zip](https://github.com/pihome-shc/pihome/files/4786379/zone.zip)

**Comment by twa127** [comment]
you are right this is causing a problem with zone.php, I'll investigate

**Comment by twa127** [comment]
checked with @pihome-shc and zone.boiler_id is not used, so I'll include the required change to zone.php in next commit

**Pull request closed without merging**
