### PR TITLE
Ability to Add and Delete Boost Options

### PR DESCRIPTION
**Pull request by dvdcut**
sorry if i mess-up something m no export on GitHub
Settings->Boost:  you can delete exiting Boost options and Add if needed.
This update applies for issues 
#46

### CODE REVIEW

**Comment by pihome-shc** [comment]
@dvdcut Thank you for update.

**Comment by twa127** [comment]
Question - do you expect to have multiple boosts for the same zone or will it be a single boost setting per zone?

**Comment by dvdcut** [comment]
yes, you can have multiple boosts for any zone, original code was there to have multiple boost but no option to add/delete from gui so i added that option.

**Comment by twa127** [comment]
Great thanks for the info, I'm working on an update to make the gui editable as well

**Comment by pihome-shc** [comment]
@twa127 that is great i have created issue for this,  can you please link your pull request to issue #61

**Pull request merged**
